package com.game.enums;

public enum GenreEnum {
	ACCION, RPG, AVENTURA, BAILE, BATTLEROYALE, ESTRATEGIA, FPS, LUCHA, MMO, MMORPG, MOBA, PLATAFORMAS, SIGILO,
	SIMULACION, SURVIVAL, MUNDOABIERTO, CARRERAS
}
